# Generated by Django 5.1.6 on 2025-03-09 03:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owners',
            field=models.ManyToManyField(
                null=True, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Owners'),
        ),
    ]
