# Generated by Django 5.1.6 on 2025-02-08 22:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Database',
                'verbose_name_plural': 'Databases',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depreciation', models.DecimalField(
                    decimal_places=2, max_digits=5)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='equipment', to='databases.database')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'unique_together': {('code', 'database')},
            },
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('hourly_cost', models.DecimalField(
                    decimal_places=2, max_digits=10)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='labor', to='databases.database')),
            ],
            options={
                'verbose_name': 'Labor',
                'verbose_name_plural': 'Labor',
                'unique_together': {('code', 'database')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='materials', to='databases.database')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='unit_material', to='databases.unit')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'unique_together': {('code', 'database')},
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('unit', models.CharField(max_length=50)),
                ('yield_rate', models.DecimalField(
                    decimal_places=2, max_digits=10)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='work_items', to='databases.database')),
                ('equipment', models.ManyToManyField(to='databases.equipment')),
                ('labor', models.ManyToManyField(to='databases.labor')),
                ('materials', models.ManyToManyField(to='databases.material')),
            ],
            options={
                'verbose_name': 'Work Item',
                'verbose_name_plural': 'Work Items',
                'unique_together': {('code', 'database')},
            },
        ),
    ]
