# Generated by Django 5.1.6 on 2025-03-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_database_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='covening_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='material_unit_usage',
            field=models.CharField(choices=[('UNITARY', 'Unitario'), (
                'DIVIDED', 'Dividido por la cantidad')], default='UNITARY', max_length=10),
        ),
    ]
