# Generated by Django 5.1.6 on 2025-03-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0003_workitem_covening_code_workitem_material_unit_usage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workitem',
            old_name='materials',
            new_name='material',
        ),
    ]
