# Generated by Django 5.1.6 on 2025-02-11 23:54

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('contract', models.CharField(max_length=100)),
                ('budget_date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('calculated_by', models.CharField(max_length=100)),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=8.0, max_digits=5,
                 validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[
                 ('BS', 'Bolivares'), ('USD', 'Dollars'), ('SOL', 'Solana')], default='USD', max_length=3)),
                ('use_associated_cost_factor', models.BooleanField(default=False)),
                ('direct_labor_factor', models.DecimalField(decimal_places=2, default=1005.0,
                 max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('iva_type', models.CharField(choices=[('NO_IVA', 'No IVA'), ('PRESUPUESTO_VALUACION', 'Budget and Valuation'), ('SOLO_VALUACION', 'Valuation Only'), (
                    'TOTAL_APU', 'APU Total'), ('MATERIALES', 'Materials'), ('MATERIALES_EQUIPOS', 'Materials and Equipment')], default='PRESUPUESTO_VALUACION', max_length=50)),
                ('iva_percentage', models.DecimalField(decimal_places=2, default=12.0, max_digits=5,
                 validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('administration_percentage', models.DecimalField(decimal_places=2, default=16.0,
                 max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('utility_percentage', models.DecimalField(decimal_places=2, default=15.0,
                 max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('financing_percentage', models.DecimalField(decimal_places=2, default=0.0,
                 max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('use_medical_insurance', models.BooleanField(default=False)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='reviewed_budgets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(
                    decimal_places=2, default=0.0, max_digits=12)),
                ('salary_limit_per_day', models.DecimalField(
                    decimal_places=2, default=0.0, max_digits=12)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='bonds', to='budgets.budget')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Retention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('retention_type', models.CharField(choices=[('ADVANCE', 'Advance'), (
                    'LABOR', 'Labor Retention'), ('COMPLIANCE', 'Compliance Retention')], max_length=20)),
                ('amount', models.DecimalField(
                    decimal_places=2, default=0.0, max_digits=12)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5,
                 validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='retentions', to='budgets.budget')),
            ],
            options={
                'ordering': ['retention_type'],
            },
        ),
    ]
