# Generated by Django 5.1.6 on 2025-03-08 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budget_work_item'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='company',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
