# Generated by Django 5.1.6 on 2025-03-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_budget_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='state',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), (
                'FINISHED', 'Finished')], default='IN_PROGRESS', max_length=20),
        ),
    ]
