# Generated by Django 5.1.6 on 2025-04-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_alter_budget_iva_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='calculated_by',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='owner',
        ),
    ]
